-- 1. Create Company Settings Table
create table if not exists company_settings (
  id uuid default gen_random_uuid() primary key, -- Use gen_random_uuid() for Supabase
  name text not null default 'Minha Empresa',
  address text,
  phone text,
  email text,
  website text,
  cnpj text,
  logo_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table company_settings enable row level security;

-- Create Policies (Public Access for Demo purposes)
create policy "Enable read access for all users" on company_settings for select using (true);
create policy "Enable update access for all users" on company_settings for update using (true) with check (true);
create policy "Enable insert access for all users" on company_settings for insert with check (true);

-- Insert default row (idempotent)
insert into company_settings (name)
select 'Panorama Molduras'
where not exists (select 1 from company_settings);

-- 2. Create Quotes Table
create table if not exists quotes (
  id uuid default gen_random_uuid() primary key,
  sequence_id bigint generated by default as identity, -- Sequential ID (1, 2, 3...)
  customer_name text,
  customer_contact text,
  total_amount numeric,
  status text default 'COMPLETED',
  items jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table quotes enable row level security;

-- Create Policies
create policy "Enable read access for all users" on quotes for select using (true);
create policy "Enable insert access for all users" on quotes for insert with check (true);
create policy "Enable update access for all users" on quotes for update using (true);

-- 3. (Optional) Create Storage Bucket for Logos if needed
-- insert into storage.buckets (id, name, public) values ('logos', 'logos', true) on conflict do nothing;
-- create policy "Public Access" on storage.objects for select using ( bucket_id = 'logos' );
-- create policy "Public Insert" on storage.objects for insert with check ( bucket_id = 'logos' );
